/*!
 * Generated by ActivePresenter 6.1.0 HTML5 (2017.04.11)
 */
﻿/*!
 * Atomi HTML5 Player - Template parameters
 * Copyright (c) Atomi Systems, Inc. All rights reserved.
 * http://atomisystems.com
 * Created: 2008/01/20
 * Modified: 2016/03/25
 */

var PrezInfo = {
	Name:"OpenCMISS Libraries Building from Source Intro",
	Description:"",
	Date1: "07/10/2017",
	Author:"Hugh Sorby",
	Copyright:"",
	Homepage:"",
	RLVersion: "6.1.0",
	AppHomePage: "https://atomisystems.com",
	ViewPort: {width:1920, height:1080},
	Language: "en-US",
	TextDir: "ltr",
	Generator: "ActivePresenter 6.1.0"
};

// LMS package type (Don't change these values)
PackageType = {
	NONE: 0,
	SCORM: 1,
	TINCAN: 2
};

var Options = {"ShowReport":true,"HilightFocus":true,"language_id":60,"ConfirmRestart":false,"GenPreview":false,"GenerateSeparatePackage":true,"AllowNavigate":false,"use_webm_ogg":false,"opmodes":2,"test_max_time":0,"report_format":0,"pass_value":80,"FlashABSpeed":0,"allow_select_text":true,"ScormScorePercent":false,"pass_condition":0,"report_value":"","image_format":"png","report_method":0,"UseAccText":true,"ExportHTML5":true};
var TemplateParams = {
   Color1:"rgb(32, 32, 32)",
   ShowPosition:true,
   ShowSlideAsGroup:true,
   DockPaneSize:250,
   IniCCShow:0,
   ShowDuration:2,
   IniVolume:80,
   ShowInfoBtn:false,
   ShowDetailedStepsInPractice:1,
   ShowNextBtn:false,
   ShowCCBtn:true,
   ImagePath:"player/images/",
   SlideListPos:2,
   ShowPrezLen:true,
   ShowLastBtn:false,
   ShowSegments:true,
   ToolbarHeight:28,
   HighLevelStepText:true,
   ShowZoomBtn:true,
   Color3:"rgb(255, 0, 0)",
   ShowVolumeBar:true,
   Color2:"rgb(255, 255, 255)",
   ShowSpeedBtn:true,
   ShowSlideListBtn:true,
   IniAutoFit:1,
   ShowVolumeBtn:true,
   ShowPrevBtn:false,
   IniSlideListShow:1,
   ShowFirstBtn:true,
   NavInPractice:true,
   ShowPlayBtn:true,
   AlwaysShowSlideList:true
}
;
var bSendToLMS = false;
var ePackageType = PackageType.NONE;
 
var PlayModes = {
	DEMO:	1,
	TUT:	2,
	PRAC:	4,
	TEST:	8
};

var UIPos = {
	//These correspond to value list in manifest
	TOP: 0,
	LEFT: 1,
	RIGHT: 2,
	BOTTOM: 3,
	FLOATING: 4,
	NONE: 5
};

/* Tin Can configuration */

// ActivityID that is sent for the statement's object
var TINCAN_COURSE_ID = "";

// CourseName for the activity
var TINCAN_COURSE_NAME = {"en-US": ""};

// CourseDesc for the activity
var TINCAN_COURSE_DESC = {"en-US": ""};

// Pre-configured LRSes that should receive data, added to what is included
// in the URL and/or passed to the constructor function.
//
// An array of objects where each object may have the following properties:
//
//    endpoint: (including trailing slash '/')
//    auth:
//    allowFail: (boolean, default true)
//    version: (string, defaults to high version supported by TinCanJS)
var TINCAN_RECORD_STORES = [];
